- name: Install patch library to build nokogiri gem
  apt: "pkg=patch state=installed"

- name: Install nodejs (needed because of execjs)
  apt: "pkg=nodejs state=installed"

- name: install ruby dependencies
  command: bash -lc 'bundle install' chdir={{ base_path }}
  sudo_user: vagrant